name: mogrify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install inkscape
        run: |
          sudo apt update
          sudo apt -y install inkscape

      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Convert SVG to PNG
        run: |
          Rename-Item ./run.ps2 ./run.ps1
          ./run.ps1
        shell: pwsh

      - name: Commit changes
        run: |
          git config --global user.email "danijel@repasscloud.com"
          git config --global user.name "RePass Cloud Pty Ltd"
          git add .
          git commit -m "Added new file"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}